# https://www.stackage.org/lts-22.6
resolver: ghc-9.6.3

packages:
- .

extra-deps:
- flow-2.0.0.4@sha256:c0b4ff962f463760112d70b6d85cc7583222505e988b5d043997db9d608713f3,1305
- parallel-3.2.2.0@sha256:b993406e98fe9126eff4a69d28e7e361037dd1c0892a9fd6c26e1f92eb9c4fa4,1926

flags: {}

extra-package-dbs: []

nix:
  enable: true
  pure: true
  packages:
  - zlib
  - glpk
  - pcre
  #shell-file: shell.nix
  nix-shell-options: []
  path: []
  add-gc-roots: false
