# https://www.stackage.org/lts-22.6
resolver: lts-22.11

packages:
- .

extra-deps:
- flow
- parallel

flags: {}

extra-package-dbs: []

nix:
  enable: true
  pure: true
  packages:
  - zlib
  - glpk
  - pcre
  #shell-file: shell.nix
  nix-shell-options: []
  path: []
  add-gc-roots: false
