name:         learnyouahaskell
version:      0.1.0.0
github:       "mingyuchoo/learnyouahaskell"
license:      BSD3
author:       "Mingyu Choo"
maintainer:   "mingyuchoo@gmail.com"
copyright:    "2023 Mingyu Choo"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mingyuchoo/learnyouahaskell#readme>

dependencies:
- base >= 4.9.1.0 && < 5
- bytestring
- containers
- directory
- flow
- mtl
- parallel
- random

default-extensions:
- ExplicitForAll
- OverloadedStrings
- StandaloneKindSignatures

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wmissing-signatures
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-binds
- -Wunused-imports

library:
  source-dirs: src

executables:
  learnyouahaskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - learnyouahaskell

tests:
  learnyouahaskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - learnyouahaskell
    - hspec
    - doctest
    - doctest-discover
