name: unit-tests
on: [push, pull_request]
jobs:
  tutorial-template:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
          cabal-version: 'latest'
      - run: cd tutorial-template; stack test
  learnyouahaskell:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
          cabal-version: 'latest'
      - run: cd learnyouahaskell; stack test

