name: unit-tests
on: [push, pull_request]
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: latest
          enable-stack: true
          stack-version: latest
          cabal-version: latest
      - run: cd tutorial-template; stack test
